apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
